name = "cashback-hunter-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cashback-hunter"
database_id = "9be3f10f-e4c1-44ad-bdb5-2406a51e664a"

[triggers]
crons = ["0 8 * * *"]

[vars]
FRONTEND_ORIGIN = "https://cashback-hunter.pages.dev"
